

spring:
  security.user:
    name: tristan
    password: password
  flyway:
    table: flyway_schema_history
    locations: classpath:db/migration
  datasource:
    url: jdbc:sqlite:store.db
  #  username:
  #  password:
    driver-class-name: org.sqlite.JDBC
    hibernate:
      dialect: org.sqlite.hibernate.dialect.SQLiteDialect

  data.rest.basePath: /api
