

spring:
  flyway:
    table: flyway_schema_history
    locations: classpath:db/migration
  datasource:
    url: jdbc:sqlite:store.db
  #  username:
  #  password:
    driver-class-name: org.sqlite.JDBC
    hibernate:
      dialect: org.sqlite.hibernate.dialect.SQLiteDialect
#      hbm2ddl.auto: create-drop
#      show_sql: true
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    generate-ddl: true
#    hibernate.ddl-auto: update

