env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  linebreak-style: ["error", "windows"],
  import/no-import-module-exports: ["off"]
}
